unbind r
bind r source-file ~/.tmux.conf

set -g base-index 3 # start windows numbering at 1

set -g prefix C-a
# act like vim
setw -g mode-keys vi
# bind -r ^ last-window
# bind -n C-h select-pane -L
# bind -n C-j select-pane -D
# bind -n C-k select-pane -U
# bind -n C-l select-pane -R
# List of plugins
set -g @plugin 'tmux-plugins/tpm'


set -g @plugin 'christoomey/vim-tmux-navigator'

set -g @plugin 'dreamsofcode-io/catppuccin-tmux'

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " █"
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"

set -g @catppuccin_status_modules_right "directory date_time"
set -g @catppuccin_status_modules_left "session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_status_right_separator_inverse "no"
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"
set -g @catppuccin_directory_text "#{b:pane_current_path}"

set -g @catppuccin_date_time_text "%H:%M"

set -g @catppuccin_window_status_style "rounded" # can comment this out

set -g status-position top

bind C-y display-popup \
  -d "#{pane_current_path}" \
  -w 80% \
  -h 80% \
  -E "lazygit"
bind C-n display-popup -E 'bash -i -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

unbind Up
unbind Down
unbind Left
unbind Right
bind K resize-pane -U 5
bind J resize-pane -D 5
bind H resize-pane -L 5
bind L resize-pane -R 5

bind d display-menu -T "#[align=centre]Dotfiles" -x C -y C \
  ".zshrc"            z  "display-popup -E 'nvim ~/.zshrc'" \
  ".tmux.conf"        t  "display-popup -E 'nvim ~/.tmux.conf'" \
  "Exit"              q  ""

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
